OBJECT_NAME: /[a-zA-Z_][a-zA-Z0-9_]*/
CREATE_QUERY: "CREATE"
UPDATE_QUERY: "UPDATE"
DROP_QUERY: "DROP"
//TOKEN:
TYPE: "int"|"string"|"boolean"

//REGLA:
field_block: "(" field* ")"

field: OBJECT_NAME TYPE ";"

//METODOS:
//* 0 o mas
//+ 1 o mas
//A? Opcional
//?A Si una regla no tiene sentido tener su propio arbol
//(A B)+ grupo que se repite
//. -> <funcion> llamar a una función especifica


//%left A B dar prioridad entre reglar